# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ReporterExample' do

pod 'Reporter', :path => '../ReporterLibrary'

end

target 'ReporterExampleTests' do

end

target 'ReporterExampleUITests' do

end

